.TH "OSKAR_SETTINGS_GET" "1" "August 2016" "oskar"
.SH NAME
oskar_settings_get \- Get value from OSKAR settings file
.SH "SYNOPSIS"
.PP
\fBoskar_settings_get\fR [OPTIONS] <settings file> <key>
.SH DESCRIPTION
Returns the value of the given key in an OSKAR settings file.
.SH OPTIONS
.TP
\fB\-\-help\fR
Display usage instructions and exit.
.TP
\fB\-\-version\fR
Display the program name/version banner and exit.
.SH COPYRIGHT
OSKAR (version 2.6.1)
Copyright \(co 2014, The University of Oxford.
This program is free and without warranty.
