.TH "OSKAR_CONVERT_CST_TO_SCALAR" "1" "August 2016" "oskar"
.SH NAME
oskar_convert_cst_to_scalar \- Convert CST to OSKAR scalar element pattern
.SH "SYNOPSIS"
.PP
\fBoskar_convert_cst_to_scalar\fR  <input CST file> <output scalar file>
.SH DESCRIPTION
Convert polarised CST element files to OSKAR scalar element pattern format.
.SH COPYRIGHT
OSKAR (version 2.6.1)
Copyright \(co 2014, The University of Oxford.
This program is free and without warranty.
