.TH "OSKAR_VIS_ADD" "1" "August 2016" "oskar"
.SH NAME
oskar_vis_add \- Combine OSKAR binary visibility files
.SH "SYNOPSIS"
.PP
\fBoskar_vis_add\fR [OPTIONS] <OSKAR visibility files...>
.SH DESCRIPTION
Application to combine OSKAR binary visibility files.
.SH OPTIONS
.TP
\fB\-o\fR, \fB\-\-output\fR \fIARG\fR
Output visibility file name (default = out.vis)
.TP
\fB\-q\fR, \fB\-\-quiet\fR
Disable log messages
.TP
\fB\-\-help\fR
Display usage instructions and exit.
.TP
\fB\-\-version\fR
Display the program name/version banner and exit.
.SH COPYRIGHT
OSKAR (version 2.6.1)
Copyright \(co 2014, The University of Oxford.
This program is free and without warranty.
