.TH "OSKAR_CUDA_SYSTEM_INFO" "1" "August 2016" "oskar"
.SH NAME
oskar_cuda_system_info \- Display available CUDA capability
.SH "SYNOPSIS"
.PP
\fBoskar_cuda_system_info\fR [OPTIONS]
.SH DESCRIPTION
Display a summary of the available CUDA capability
.SH OPTIONS
.TP
\fB\-\-help\fR
Display usage instructions and exit.
.TP
\fB\-\-version\fR
Display the program name/version banner and exit.
.SH COPYRIGHT
OSKAR (version 2.6.1)
Copyright \(co 2014, The University of Oxford.
This program is free and without warranty.
