.TH "OSKAR" "1" "August 2016" "oskar"
.SH NAME
oskar \- Main OSKAR GUI application
.SH "SYNOPSIS"
.PP
\fBoskar\fR [OPTIONS] [settings file]
.SH DESCRIPTION
GUI application providing an interface for editing OSKAR settings files
and launching OSKAR application binaries.
.SH OPTIONS
.TP
\fB\-\-help\fR
Display usage instructions and exit.
.TP
\fB\-\-version\fR
Display the program name/version banner and exit.
.SH COPYRIGHT
OSKAR (version 2.6.1)
Copyright \(co 2014, The University of Oxford.
This program is free and without warranty.
