.TH "OSKAR_SIM_INTERFEROMETER" "1" "August 2016" "oskar"
.SH NAME
oskar_sim_interferometer \- Perform interferometry simulations. 
.SH "SYNOPSIS"
.PP
\fBoskar_sim_interferometer\fR [OPTIONS] <settings file>
.SH DESCRIPTION
Command line application for interferometry simulations. 
.SH OPTIONS
.TP
\fB\-q\fR, \fB\-\-quiet\fR
Suppress printing.
.TP
\fB\-\-help\fR
Display usage instructions and exit.
.TP
\fB\-\-version\fR
Display the program name/version banner and exit.
.SH COPYRIGHT
OSKAR (version 2.6.1)
Copyright \(co 2014, The University of Oxford.
This program is free and without warranty.
