.TH "OSKAR_IMAGER" "1" "August 2016" "oskar"
.SH NAME
oskar_imager \- Simple DFT imaging
.SH "SYNOPSIS"
.PP
\fBoskar_imager\fR [OPTIONS] <settings file>
.SH DESCRIPTION
Command line application for simple DFT imaging.
.SH OPTIONS
.TP
\fB\-q\fR, \fB\-\-quiet\fR
Suppress printing.
.TP
\fB\-\-help\fR
Display usage instructions and exit.
.TP
\fB\-\-version\fR
Display the program name/version banner and exit.
.SH COPYRIGHT
OSKAR (version 2.6.1)
Copyright \(co 2014, The University of Oxford.
This program is free and without warranty.
