.TH "OSKAR_VIS_UPGRADE_FORMAT" "1" "August 2016" "oskar"
.SH NAME
oskar_vis_upgrade_format \- OSKAR visibility file format upgrade
.SH "SYNOPSIS"
.PP
\fBoskar_vis_uprade_format\fR [OPTIONS] <OSKAR visibility files...>
.SH DESCRIPTION
Upgrades one or more old OSKAR visibility binary files to the current
format version.
.SH OPTIONS
.TP
\fB\-\-help\fR
Display usage instructions and exit.
.TP
\fB\-\-version\fR
Display the program name/version banner and exit.
.SH COPYRIGHT
OSKAR (version 2.6.1)
Copyright \(co 2014, The University of Oxford.
This program is free and without warranty.
