.TH "OSKAR_VIS_SUMMARY" "1" "August 2016" "oskar"
.SH NAME
oskar_vis_summary \- OSKAR visibility file summary
.SH "SYNOPSIS"
.PP
\fBoskar_vis_summary\fR [OPTIONS] <OSKAR visibility file>
.SH DESCRIPTION
Displays a summary and optional statistics of data within an OSKAR visibility file.
.SH OPTIONS
.TP
\fB\-l\fR, \fB\-\-log\fR
Display the simulation log.
.TP
\fB\-s\fR, \fB\-\-settings\fR
Display the simulation settings file.
.TP
\fB\-t\fR, \fB\-\-stats\fR
Display visibility statistics.
.TP
\fB\-a\fR, \fB\-\-header\fR
Display header.
.TP
\fB\-\-help\fR
Display usage instructions and exit.
.TP
\fB\-\-version\fR
Display the program name/version banner and exit.
.SH COPYRIGHT
OSKAR (version 2.6.1)
Copyright \(co 2014, The University of Oxford.
This program is free and without warranty.
